codecov:
  notify:
    require_ci_to_pass: yes
  token: 585c5732-0cdc-4624-b77f-b21ec66f9c4b

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
